### ISSUE TITLE
Request for Assignment of Tasks

### ISSUE THREAD

**Issue by Jay-Shah0** [ZEviod/open-source-mern#11]
I noticed that there seems to be a lull in ongoing projects and people who are assigned the issues not completed yet so if possible is there are any tasks or responsibilities that could be assigned to me during this time. I’m eager to contribute and help wherever possible.

Thank you for considering my request. I look forward to your guidance.

**Comment by ZEviod** [comment]
@Jay-Shah0 wait for some time, will think on it and let you know, untill you resolve your assigned issue

**Comment by ive-not** [comment]
I am also willing to work on them
