### ISSUE TITLE
Create a Comprehensive "Contact Us" Page

### ISSUE THREAD

**Issue by ZEviod** [ZEviod/open-source-mern#5]
We need to develop a well-structured "Contact Us" page to enhance user engagement and facilitate effective communication with our customers. The page should include the following elements:

Requirements:

Contact Form:
Name field
Email address field
Phone number field
Message/inquiry field
Subject dropdown (optional)

Contact Information:
Phone number
Email address
Include icons/links to our social media profiles.

FAQ Section:
Address common queries to reduce direct inquiries.

Privacy Statement:
Briefly mention how user data will be used and assure confidentiality.

Response Time Information:
Inform users when they can expect a reply.

for now put dummy data

**Comment by NinaVincova** [comment]
Hello :) It is possible to work on this issue? Can it be assigned?

**Comment by mahirabidi12** [comment]
Please assign me this issue , as you said earlier.

**Comment by ZEviod** [comment]
okay i will assign it to both, but the better one will be accepted!

**Comment by ZEviod** [comment]
i hope you both know rules and procedure to contribute to open source

**Comment by ive-not** [comment]
Can you assign me under hacktoberfest

**Comment by ZEviod** [comment]
Completed!
