### ISSUE TITLE
Home Page Development

### ISSUE THREAD

**Issue by ZEviod** [ZEviod/open-source-mern#7]
Create the Home page of the app. This page will serve as the main tour guide for users, introducing them to the app's features and functionalities.

Acceptance Criteria:
Engaging introduction to the app
Visual tour of the main features
Easy navigation to other sections

**Comment by NinaVincova** [comment]
Hello :) It is possible to work on this issue? Can it be assigned?

**Comment by Akash-cloud001** [comment]
I can work on this assign it me, with hacktoberfest label

**Comment by ive-not** [comment]
@Akash-cloud001 are you working on it?

**Comment by Akash-cloud001** [comment]
Yes  I am working on it

**Comment by Akash-cloud001** [comment]
![IMG_7228](https://github.com/user-attachments/assets/5b465f35-cd73-458b-8983-143152c6a8d7)
![IMG_7229](https://github.com/user-attachments/assets/178c51c9-a5ec-4495-9e1c-b674717ce60d)

Am getting this issue on hacktoberfest could you please resolve this.
Thank you

**Comment by ZEviod** [comment]
@Akash-cloud001 Thank you for letting us know , I will check and let you know shortly

**Comment by ZEviod** [comment]
@Akash-cloud001 Yah we looked into the matter and found a technical bug/glitch in which it does not count the label after review, under which it is to be labeled before review 
sorry for the inconvience
either you can wait for a while if it counts in 6 hours or else if you like to you can resend a PR with small changes and we will consider it for your compensastion!

**Comment by Akash-cloud001** [comment]
Thanks for checking the issue has been resolved. Thank you
